image: 
  name: archlinux/base
  entrypoint: ["/bin/bash"]

before_script:
  - pacman -Syyu --noconfirm \
  base-devel \
  cuda \
  git \
  cmake \
  glfw \
  glm \
  glew \
  glut \
  irrlicht \
  wget \
  boost \
  fish \
  python \
  python-pip \
  openmpi \
  swig
  - ldconfig
  - wget https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.5.tar.gz
  - tar -xf blaze-3.5.tar.gz
  - cp blaze-3.5/blaze /usr/local/include
  - mkdir build

chrono_build:
  stage: deploy
  script:
  - cd build
  - cmake ../ \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_MODULE_POSTPROCESS=TRUE \
    -DENABLE_MODULE_PYTHON=TRUE \
    -DENABLE_MODULE_COSIMULATION=FALSE \
    -DENABLE_MODULE_IRRLICHT=TRUE \
    -DENABLE_MODULE_VEHICLE=TRUE \
    -DENABLE_MODULE_PARALLEL=TRUE \
    -DENABLE_MODULE_OPENGL=TRUE \
    -DCMAKE_C_COMPILER=/usr/bin/gcc
    -DCMAKE_CXX_COMPILER=/usr/bin/g++
    -DCUDA_HOST_COMPILER=/usr/bin/gcc
  - make -j 2

chrono_test:
  stage: test
  script:
  - cd build
  - make test
    
